// app/layout.tsx
import type { Metadata } from "next";
import { Montserrat, Manrope } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Toaster from "@/components/Toaster";
import { AuthProvider } from "@/contexts/AuthContext"; // Import du fournisseur d'authentification

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-montserrat",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${manrope.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
        </AuthProvider>
        <main className=" w-full font-manrope">
          <Toaster />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
